course_reg/routes.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    session,
    redirect,
    current_app,
    flash,
    request
)
from course_reg.forms import LoginForm, FilterForm, AdvancedFilterForm
from course_reg.models import Filters, AdvancedFilters
import course_reg.filter_methods
import course_reg.schedule_methods
import course_reg.register_methods
from passlib.hash import pbkdf2_sha256
import functools
from datetime import datetime, timezone


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))
        
        return route(*args, **kwargs)
    
    return route_wrapper


def check_window(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session["start_window"] > datetime.now(timezone.utc) or session["end_window"] < datetime.now(timezone.utc):
            standard_start = datetime.strptime("07:00", "%H:%M").time()
            standard_end = datetime.strptime("19:00", "%H:%M").time()
            test_now = datetime.strptime("01:00", "%H:%M").time()

            if standard_start <= test_now and standard_end >= test_now:
                return redirect(url_for(".user_courses"))
            # return redirect(url_for(".user_courses"))

        return route(*args, **kwargs)
    
    return route_wrapper


@pages.route("/")
@login_required
def index():
    course_reg.register_methods.enroll_from_waitlist()
    session["user_courses"] = course_reg.schedule_methods.get_registered_courses(session["user_id"])
    session["unreged_courses"] = []
    session["user_waitlist"] = course_reg.schedule_methods.get_waitlist(session["user_id"])
    session["temp_courses"] = []
    session["load_bearing"] = False
    session["cancel"] = False
    session["start_window"], session["end_window"] = course_reg.register_methods.get_enrollment_window(session["user_id"])
    
    return redirect(url_for(".user_courses"))


@pages.route("/courses")
@login_required
def user_courses():
    courses = course_reg.schedule_methods.get_short_courses(session["user_courses"])
    calendar = course_reg.schedule_methods.create_calendar(courses)

    if len(session["unreged_courses"]) > 0:
        flash("Could not register these courses, check if all requirements satisfied:")
        unreged = ""
        for course in session["unreged_courses"]:
            unreged += str(course) + ", "
        flash(unreged[:-2])
        session["unreged_courses"] = []

    return render_template(
        "index.html",
        title="Course Registration - My Courses",
        courses=courses,
        calendar=calendar
    )


@pages.route("/finals")
@login_required
def user_finals():
    courses = course_reg.schedule_methods.get_short_courses_final(session["user_courses"])
    calendar = course_reg.schedule_methods.create_final_calendar(courses)

    return render_template(
        "index_finals.html",
        title="Course Registration - My Finals",
        courses=courses,
        calendar=calendar
    )


@pages.route("/quarter")
@login_required
def user_quarter():
    courses = course_reg.schedule_methods.get_short_courses(session["user_courses"])

    return render_template(
        "index_quarter.html",
        title="Course Registration - Current Quarter",
        courses=courses
    )


@pages.route("/waitlists")
@login_required
def user_waitlists():
    courses = course_reg.filter_methods.get_user_waitlist(session["user_id"], session["user_waitlist"])

    return render_template(
        "waitlists.html",
        title="Course Registration - My Waitlists",
        courses=courses
    )


@pages.route("/login", methods=["GET", "POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_cursor = current_app.db.execute(
            """SELECT student_id, email, password
            FROM student
            WHERE email = :email""",
            {"email": form.email.data}
        )
        user_data = user_cursor.fetchone()
        user_cursor.close()

        if not user_data:
            flash("Login credentials not correct")
            return redirect(url_for(".login"))
        
        user_id = user_data[0]
        user_email = user_data[1]
        user_pwd = user_data[2]

        if user_data and pbkdf2_sha256.verify(form.password.data, user_pwd):
            session["user_id"] = user_id
            session["email"] = user_email

            return redirect(url_for(".index"))
        
        flash("Login credentials not correct")

    return render_template(
        "login.html",
        title="Course Registration - Login",
        form=form
    )


@pages.route("/drop-courses")
@login_required
@check_window
def drop_courses():
    courses = course_reg.filter_methods.get_courses_from_codes(session["user_courses"])

    return render_template(
        "drop_courses.html",
        title="Course Registration - Drop Courses",
        courses=courses
    )


@pages.route("/filter-courses", methods=["GET", "POST"])
@login_required
def filter_courses():
    if session["cancel"] == True:
        session["temp_courses"] = []
        session["cancel"] = False
    
    form = FilterForm()
    form.gen_cat.choices = course_reg.filter_methods.prep_ge()
    form.department.choices = course_reg.filter_methods.prep_departments()
    

    if form.validate_on_submit():
        filters = Filters(
            ge_cat=int(form.gen_cat.data),
            department=int(form.department.data),
            course_num=form.course_num.data,
            course_code=form.course_code.data,
            course_level=form.course_level.data,
            instructor=form.instructor.data
        )
        session["filter_courses"] = course_reg.filter_methods.get_courses(filters, session["temp_courses"], session["user_courses"], session["user_waitlist"])
        session["filter_criteria"] = course_reg.filter_methods.get_criteria(filters)
        return redirect(url_for(".course_listing"))

    return render_template(
        "filter_courses.html",
        title="Course Registration - Filter Courses",
        form=form
    )


@pages.route("/filter-courses/advanced", methods=["GET", "POST"])
@login_required
def filter_courses_advanced():
    form = AdvancedFilterForm()
    form.gen_cat.choices = course_reg.filter_methods.prep_ge()
    form.department.choices = course_reg.filter_methods.prep_departments()

    if form.validate_on_submit():
        filters = AdvancedFilters(
            ge_cat=int(form.gen_cat.data),
            department=int(form.department.data),
            course_num=form.course_num.data,
            course_code=form.course_code.data,
            course_level=form.course_level.data,
            instructor=form.instructor.data,
            modality=form.modality.data,
            days=form.days.data,
            starts_after=form.starts_after.data,
            ends_before=form.ends_before.data,
            course_full_option=form.course_full_option.data,
            cancel_option=form.cancel_option.data,
            building_code=form.building_code.data,
            room_no=form.room_no.data,
            credits=form.credits.data
        )
        session["filter_criteria"] = course_reg.filter_methods.get_criteria_adv(filters)
        session["filter_courses"] = course_reg.filter_methods.get_courses_adv(filters, session["temp_courses"], session["user_courses"], session["user_waitlist"])
        return redirect(url_for(".course_listing"))

    return render_template(
        "filter_courses_advanced.html",
        title="Course Registration - Filter Courses - Advanced",
        form=form
    )


@pages.route("/listings")
@login_required
def course_listing():    
    return render_template(
        "course_listing.html",
        title="Course Registration - Listings",
        criteria=session["filter_criteria"],
        courses=session["filter_courses"]
    )


@pages.route("/preview/courses")
@login_required
def preview_courses():
    courses = course_reg.schedule_methods.get_short_courses(session["temp_courses"] + session["user_courses"])
    calendar = course_reg.schedule_methods.create_calendar(courses)

    return render_template(
        "preview_courses.html",
        title="Course Registration - Preview Courses",
        courses=courses,
        calendar=calendar
    )


@pages.route("/preview/finals")
@login_required
def preview_finals():
    courses = course_reg.schedule_methods.get_short_courses_final(session["temp_courses"] + session["user_courses"])
    calendar = course_reg.schedule_methods.create_final_calendar(courses)

    return render_template(
        "preview_finals.html",
        title="Course Registration - Preview Finals",
        courses=courses,
        calendar=calendar
    )


@pages.route("/preview/quarter")
@login_required
def preview_quarter():
    courses = course_reg.schedule_methods.get_short_courses(session["temp_courses"] + session["user_courses"])

    return render_template(
        "preview_quarter.html",
        title="Course Registration - View Quarter",
        courses=courses
    )



@pages.get("/add-course/<int:code>")
@login_required
@check_window
def add_course(code):
    if code not in session["temp_courses"]:
        session["load_bearing"] = True
        session["temp_courses"].append(code)

        for course in session["filter_courses"]:
            if course[1] == code:
                course[0] = "Registered"
                break

course_reg/templates/course_listing.html
{% from "macros/nav.html" import header %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/listing.css') }}" />
{% endblock %}

{% block header_content %}
    {{ header() }}
{% endblock %}

{% block main_content %}
    <h1 class="listing__title">Course Listings</h1>

    <div class="criteria">
        <p class="criteria__heading">Criteria:</p>
        <ul class="criteria__list">
            {% for criterion in criteria %}
                <li>{{ criterion }}</li>
            {% endfor %}
        </ul>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th class="table__header">Add / Drop</th>
                <th class="table__header">Course Code</th>
                <th class="table__header">Course Name</th>
                <th class="table__header">Abbreviation</th>
                <th class="table__header">School</th>
                <th class="table__header">Type</th>
                <th class="table__header">Credits</th>
                <th class="table__header">Instructor</th>
                <th class="table__header">Modality</th>
                <th class="table__header">Days</th>
                <th class="table__header">Time</th>
                <th class="table__header">Location</th>
                <th class="table__header">Final</th>
                <th class="table__header">Status</th>
                <th class="table__header">Seats Taken</th>
            </tr>
        </thead>

        <tbody>
            {% for course in courses %}
                <tr>
                    {% for item in course %}
                        {% if loop.first %}
                            {% if item == "Registered" %}
                                <td class="table__item"><a href="{{ url_for('pages.drop_course', code=course[1], current_page=request.path) }}" class="table__link">Drop</a></td>
                            {% elif item == "Waitlisted" %}
                                <td class="table__item"><a href="{{ url_for('pages.drop_wait', code=course[1], current_page=request.path) }}" class="table__link">DropW</a></td>
                            {% else %}
                                {% if course[-2] == "Waitlist" %}
                                    <td class="table__item"><a href="{{ url_for('pages.wait_course', code=course[1], current_page=request.path) }}" class="table__link">Wait</a></td>
                                {% elif course[-2] == "Open" %}
                                    <td class="table__item"><a href="{{ url_for('pages.add_course', code=course[1], current_page=request.path) }}" class="table__link">Add</a></td>
                                {% else %}
                                    <td class="table__item">Full</td>
                                {% endif %}
                            {% endif %}
                        {% else %}
                            <td class="table__item">{{ item }}</td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="listing__nav">
        <a href="{{ url_for('pages.cancel_select') }}" class="listing__nav--button">
            <p class="listing__nav--text">Cancel</p>
        </a>

        <a href="{{ url_for('pages.filter_courses') }}" class="listing__nav--button">
            <p class="listing__nav--text">Add More Courses</p>
        </a>

        <a href="{{ url_for('pages.preview_courses') }}" class="listing__nav--button">
            <p class="listing__nav--text">View Schedule</p>
        </a>
    </div>
{% endblock %}

course_reg/templates/drop_courses.html
{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/listing.css') }}" />
{% endblock %}

{% block main_content %}
    <h1 class="listing__title">Drop Courses</h1>

    <table class="table">
        <thead>
            <tr>
                <th class="table__header">Drop</th>
                <th class="table__header">Course Code</th>
                <th class="table__header">Course Name</th>
                <th class="table__header">Abbreviation</th>
                <th class="table__header">School</th>
                <th class="table__header">Type</th>
                <th class="table__header">Credits</th>
                <th class="table__header">Instructor</th>
                <th class="table__header">Modality</th>
                <th class="table__header">Days</th>
                <th class="table__header">Time</th>
                <th class="table__header">Location</th>
                <th class="table__header">Final</th>
                <th class="table__header">Status</th>
                <th class="table__header">Seats Taken</th>
            </tr>
        </thead>

        <tbody>
            {% for course in courses %}
                <tr>
                    {% for item in course %}
                        {% if loop.first %}
                            {% if item == "Registered" %}
                                <td class="table__item"><a href="{{ url_for('pages.drop_course', code=course[1], current_page=request.path) }}" class="table__link">Drop</a></td>
                            {% else %}
                                <td class="table__item">Dropped</td>
                            {% endif %}
                        {% else %}
                            <td class="table__item">{{ item }}</td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="listing__nav">
        <a href="{{ url_for('pages.user_courses') }}" class="listing__nav--button">
            <p class="listing__nav--text">Back to Courses</p>
        </a>
    </div>
{% endblock %}

course_reg/templates/filter_courses.html
{% from "macros/nav.html" import header %}
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}

<!-- Basics: Department, number, code, instructor, GE category -->
<!-- Advanced: Days, Start time, end time, credits -->

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/filter.css') }}" />
{% endblock %}

{% block header_content %}
    {{ header() }}
{% endblock %}

{% block main_content %}
    <h1 class="form__title">Courses Search & Registration Portal</h1>

    <form name="course-filter" method="post" class="form">
        <div class="form__container">
            {{ form.hidden_tag() }}

            <div class="form__half">
                {{ render_text_field(form.gen_cat) }}
                {{ render_text_field(form.course_num) }}
                {{ render_text_field(form.course_level) }}

                <div class="form__showhide form__show">
                    <a href="{{ url_for('pages.filter_courses_advanced') }}" class="form__showhide--text">+ Advanced Search Options</a>
                </div>
            </div>

            <div class="form__half">
                {{ render_text_field(form.department) }}
                {{ render_text_field(form.course_code) }}
                {{ render_text_field(form.instructor) }}

                <div>
                    {{ form.submit(class_="button button--basic-filter") }}
                </div>
            </div>
        </div>
    </form>
{% endblock %}

course_reg/templates/filter_courses_advanced.html
{% from "macros/nav.html" import header %}
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}

<!-- Basics: Department, number, code, instructor, GE category -->
<!-- Advanced: Days, Start time, end time, credits -->

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/filter.css') }}" />
{% endblock %}

{% block header_content %}
    {{ header() }}
{% endblock %}

{% block main_content %}
    <h1 class="form__title">Courses Search & Registration Portal</h1>

    <form name="course-filter" method="post" class="form">
        <div class="form__container">
            {{ form.hidden_tag() }}

            <div class="form__half">
                {{ render_text_field(form.gen_cat) }}
                {{ render_text_field(form.course_num) }}
                {{ render_text_field(form.course_level) }}
            </div>

            <div class="form__half">
                {{ render_text_field(form.department) }}
                {{ render_text_field(form.course_code) }}
                {{ render_text_field(form.instructor) }}
            </div>
        </div>

        <div class="form__showhide form__hide">
            <a href="{{ url_for('pages.filter_courses') }}" class="form__showhide--text">- Advanced Search Options</a>
        </div>

        <div class="form__container">
            {{ form.hidden_tag() }}

            <div class="form__half">
                {{ render_text_field(form.modality) }}
                {{ render_text_field(form.starts_after) }}
                {{ render_text_field(form.course_full_option) }}
                {{ render_text_field(form.building_code) }}
                {{ render_text_field(form.credits) }}
            </div>

            <div class="form__half">
                {{ render_text_field(form.days) }}
                {{ render_text_field(form.ends_before) }}
                {{ render_text_field(form.cancel_option) }}
                {{ render_text_field(form.room_no) }}

                <div style="padding-top: 21%;">
                    {{ form.submit(class_="button button--adv-filter") }}
                </div>
            </div>
        </div>
        
    </form>
{% endblock %}

course_reg/templates/index.html
{% from "macros/schedules.html" import courses_schedule %}
{% from "macros/short_courses.html" import courses_short %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/schedule.css') }}" />
{% endblock %}

{% block main_content %}
    <div class="schedule__container">
        <div class="schedule__half">
            <div class="schedule__nav">
                <a href="{{ url_for('pages.user_courses') }}" class="schedule__link">Weekly Schedule</a>
                <a href="{{ url_for('pages.user_finals') }}" class="schedule__link">Final Schedule</a>
                <a href="{{ url_for('pages.user_quarter') }}" class="schedule__link">Quarterly Calendar</a>
            </div>

            {{ courses_schedule(calendar) }}
        </div>

        <hr />

        <div class="schedule__half">
            <div class="schedule__messages">
                {% with messages = get_flashed_messages() %}
                    {% for message in messages %}
                        <p class="schedule__flash">{{ message }}</p>
                    {% endfor %}
                {% endwith %}
            </div>

            <h1 class="schedule__title">My Courses</h1>

            {{ courses_short(courses) }}

            <div class="schedule__nav">
                <a href="{{ url_for('pages.filter_courses') }}" class="schedule__link">Add Courses</a>
                <a href="{{ url_for('pages.drop_courses') }}" class="schedule__link">Drop Courses</a>
                <a href="{{ url_for('pages.user_waitlists') }}" class="schedule__link">See Waitlist</a>
            </div>
        </div>
    </div>
{% endblock %}

course_reg/templates/index_finals.html
{% from "macros/schedules.html" import finals_schedule %}
{% from "macros/short_courses.html" import finals_short %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/schedule.css') }}" />
{% endblock %}

{% block main_content %}
    <div class="schedule__container">
        <div class="schedule__half">
            <div class="schedule__nav">
                <a href="{{ url_for('pages.user_courses') }}" class="schedule__link">Weekly Schedule</a>
                <a href="{{ url_for('pages.user_finals') }}" class="schedule__link">Final Schedule</a>
                <a href="{{ url_for('pages.user_quarter') }}" class="schedule__link">Quarterly Calendar</a>
            </div>

            {{ finals_schedule(calendar) }}
        </div>

        <hr />

        <div class="schedule__half">
            <h1 class="schedule__title">My Courses</h1>

            {{ finals_short(courses) }}

            <div class="schedule__nav">
                <a href="{{ url_for('pages.filter_courses') }}" class="schedule__link">Add Courses</a>
                <a href="{{ url_for('pages.drop_courses') }}" class="schedule__link">Drop Courses</a>
                <a href="{{ url_for('pages.user_waitlists') }}" class="schedule__link">See Waitlist</a>
            </div>
        </div>
    </div>
{% endblock %}

course_reg/templates/index_quarter.html
{% from "macros/short_courses.html" import courses_short %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/schedule.css') }}" />
{% endblock %}

{% block main_content %}
    <div class="schedule__container">
        <div class="schedule__half">
            <div class="schedule__nav">
                <a href="{{ url_for('pages.user_courses') }}" class="schedule__link">Weekly Schedule</a>
                <a href="{{ url_for('pages.user_finals') }}" class="schedule__link">Final Schedule</a>
                <a href="{{ url_for('pages.user_quarter') }}" class="schedule__link">Quarterly Calendar</a>
            </div>

            <img src="{{ url_for('static', filename='Fall-2024.png') }}" class="schedule__quarter" />
        </div>

        <hr />

        <div class="schedule__half">
            <h1 class="schedule__title">Selected Courses</h1>

            {{ courses_short(courses) }}

            <div class="schedule__nav">
                <a href="{{ url_for('pages.filter_courses') }}" class="schedule__link">Add Courses</a>
                <a href="{{ url_for('pages.drop_courses') }}" class="schedule__link">Drop Courses</a>
                <a href="{{ url_for('pages.user_waitlists') }}" class="schedule__link">See Waitlist</a>
            </div>
        </div>
    </div>
{% endblock %}

course_reg/templates/preview_courses.html
{% from "macros/schedules.html" import courses_schedule %}
{% from "macros/short_courses.html" import courses_short %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/schedule.css') }}" />
{% endblock %}

{% block main_content %}
    <div class="schedule__container">
        <div class="schedule__half">
            <div class="schedule__nav">
                <a href="{{ url_for('pages.preview_courses') }}" class="schedule__link">Weekly Schedule</a>
                <a href="{{ url_for('pages.preview_finals') }}" class="schedule__link">Final Schedule</a>
                <a href="{{ url_for('pages.preview_quarter') }}" class="schedule__link">Quarterly Calendar</a>
            </div>

            {{ courses_schedule(calendar) }}
        </div>

        <hr />

        <div class="schedule__half">
            <h1 class="schedule__title">Selected Courses</h1>

            {{ courses_short(courses) }}

            <div class="schedule__nav">
                <a href="{{ url_for('pages.cancel_select') }}" class="schedule__link">Cancel</a>
                <a href="{{ url_for('pages.filter_courses') }}" class="schedule__link">Add More Courses</a>
                <a href="{{ url_for('pages.confirm_schedule') }}" class="schedule__link">Confirm Schedule</a>
            </div>
        </div>
    </div>
{% endblock %}

course_reg/templates/preview_finals.html
{% from "macros/schedules.html" import finals_schedule %}
{% from "macros/short_courses.html" import finals_short %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/schedule.css') }}" />
{% endblock %}

{% block main_content %}
    <div class="schedule__container">
        <div class="schedule__half">
            <div class="schedule__nav">
                <a href="{{ url_for('pages.preview_courses') }}" class="schedule__link">Weekly Schedule</a>
                <a href="{{ url_for('pages.preview_finals') }}" class="schedule__link">Final Schedule</a>
                <a href="{{ url_for('pages.preview_quarter') }}" class="schedule__link">Quarterly Calendar</a>
            </div>

            {{ finals_schedule(calendar) }}
        </div>

        <hr />

        <div class="schedule__half">
            <h1 class="schedule__title">Selected Courses</h1>

            {{ finals_short(courses) }}

            <div class="schedule__nav">
                <a href="{{ url_for('pages.cancel_select') }}" class="schedule__link">Cancel</a>
                <a href="{{ url_for('pages.filter_courses') }}" class="schedule__link">Add More Courses</a>
                <a href="{{ url_for('pages.confirm_schedule') }}" class="schedule__link">Confirm Schedule</a>
            </div>
        </div>
    </div>
{% endblock %}

course_reg/templates/preview_quarter.html
{% from "macros/short_courses.html" import courses_short %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/schedule.css') }}" />
{% endblock %}

{% block main_content %}
    <div class="schedule__container">
        <div class="schedule__half">
            <div class="schedule__nav">
                <a href="{{ url_for('pages.preview_courses') }}" class="schedule__link">Weekly Schedule</a>
                <a href="{{ url_for('pages.preview_finals') }}" class="schedule__link">Final Schedule</a>
                <a href="{{ url_for('pages.preview_quarter') }}" class="schedule__link">Quarterly Calendar</a>
            </div>

            <img src="{{ url_for('static', filename='Fall-2024.png') }}" class="schedule__quarter" />
        </div>

        <hr />

        <div class="schedule__half">
            <h1 class="schedule__title">Selected Courses</h1>

            {{ courses_short(courses) }}

            <div class="schedule__nav">
                <a href="{{ url_for('pages.cancel_select') }}" class="schedule__link">Cancel</a>
                <a href="{{ url_for('pages.filter_courses') }}" class="schedule__link">Add More Courses</a>
                <a href="{{ url_for('pages.confirm_schedule') }}" class="schedule__link">Confirm Schedule</a>
            </div>
        </div>
    </div>
{% endblock %}

course_reg/templates/waitlists.html
{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/listing.css') }}" />
{% endblock %}

{% block main_content %}
    <h1 class="listing__title">My Waitlists</h1>

    <table class="table">
        <thead>
            <tr>
                <th class="table__header">Drop</th>
                <th class="table__header">Course Code</th>
                <th class="table__header">Course Name</th>
                <th class="table__header">Abbreviation</th>
                <th class="table__header">School</th>
                <th class="table__header">Type</th>
                <th class="table__header">Credits</th>
                <th class="table__header">Instructor</th>
                <th class="table__header">Modality</th>
                <th class="table__header">Days</th>
                <th class="table__header">Time</th>
                <th class="table__header">Location</th>
                <th class="table__header">Final</th>
                <th class="table__header">Status</th>
                <th class="table__header">Seats Taken</th>
                <th class="table__header">Current Position</th>
            </tr>
        </thead>

        <tbody>
            {% for course in courses %}
                <tr>
                    {% for item in course %}
                        {% if loop.first %}
                            {% if item == "Waitlisted" %}
                                <td class="table__item"><a href="{{ url_for('pages.drop_wait', code=course[1], current_page=request.path) }}" class="table__link">Drop</a></td>
                            {% else %}
                                <td class="table__item">Dropped</td>
                            {% endif %}
                        {% else %}
                            <td class="table__item">{{ item }}</td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="listing__nav">
        <a href="{{ url_for('pages.user_courses') }}" class="listing__nav--button">
            <p class="listing__nav--text">Back to Courses</p>
        </a>
    </div>
{% endblock %}